'use client'
import { createContext, useContext, useState, useEffect, type ReactNode } from 'react'
export type OrderStatus = 'pending' | 'processing' | 'paid' | 'delivered'
export type Order = { id: string; productId: string; productName: string; productPrice: number; userId: string; userName: string; userEmail: string; status: OrderStatus; createdAt: string; updatedAt: string; deliveryContent?: any; downloadLink?: string; licenseKey?: string; customerName?: string }
type OrdersContextType = { orders: Order[]; userOrders: Order[]; createOrder: (productId: string, productName: string, productPrice: number, userName?: string) => Order; updateOrderStatus: (orderId: string, status: OrderStatus, deliveryData?: Partial<Order>) => void; getOrderById: (orderId: string) => Order | undefined; getAllOrders: () => Order[]; deleteOrder: (orderId: string) => void; getUserOrders: (userId: string) => Order[]; deliverOrder: (orderId: string, deliveryData?: Partial<Order>) => void }
const OrdersContext = createContext<OrdersContextType | undefined>(undefined)
const generateOrderId = () => `VX-${Math.floor(10000 + Math.random() * 90000)}`
export function OrdersProvider({ children }: { children: ReactNode }) { const [orders, setOrders] = useState<Order[]>([]); const [userOrders, setUserOrders] = useState<Order[]>([]); useEffect(() => { try { const saved = localStorage.getItem('varnox-orders'); if (saved) setOrders(JSON.parse(saved)) } catch {} }, []); useEffect(() => { try { const user = JSON.parse(localStorage.getItem('varnox-user') || 'null'); setUserOrders(user ? orders.filter((o) => o.userId === user.id) : []) } catch { setUserOrders([]) } }, [orders]); const save = (next: Order[]) => { setOrders(next); localStorage.setItem('varnox-orders', JSON.stringify(next)) }; const createOrder = (productId: string, productName: string, productPrice: number, userName?: string) => { let user: any = null; try { user = JSON.parse(localStorage.getItem('varnox-user') || 'null') } catch {}; const now = new Date().toISOString(); const order: Order = { id: generateOrderId(), productId, productName, productPrice, userId: user?.id || `guest-${Date.now()}`, userName: userName || user?.name || 'Guest', customerName: userName || user?.name || 'Guest', userEmail: user?.email || '', status: 'pending', createdAt: now, updatedAt: now }; save([order, ...orders]); return order }; const updateOrderStatus = (id: string, status: OrderStatus, deliveryData?: Partial<Order>) => save(orders.map((o) => o.id === id ? { ...o, status, ...deliveryData, updatedAt: new Date().toISOString() } : o)); const deliverOrder = (id: string, _customerName?: string, data?: Partial<Order>) => updateOrderStatus(id, 'delivered', data); return <OrdersContext.Provider value={{ orders, userOrders, createOrder, updateOrderStatus, getOrderById: (id) => orders.find((o) => o.id === id), getAllOrders: () => orders, deleteOrder: (id) => save(orders.filter((o) => o.id !== id)), getUserOrders: (id) => orders.filter((o) => o.userId === id), deliverOrder }}>{children}</OrdersContext.Provider> }
export function useOrders() { const context = useContext(OrdersContext); if (!context) throw new Error('useOrders must be used within an OrdersProvider'); return context }
